name: "CI (Integração continua): Main Workflow"

on:
  pull_request:
    types: [opened, synchronieze]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Installation
    run: yarn install
    - name: Run Linter
      run: yarn lint
