name: "CI (Integração Continua) Primiera Action"

#Ativa esse fluxo de trabalho para cada push ou pull que acontecer apontando para branch main
on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created, deleted]

#     Ou então, podemos usar o filtro branches para quando alguém fizer um push para a main ou em alguma branch que começa com releases/

# on:
#   push:
#     branches:    
#       - 'main'
#       - 'releases/**'

# Definindo o que queremos executar
jobs:
  exemplo: #Job: exemplo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, word!

      # Runs a single command using the runners shell
      - name: Run a list files
        run: ls -la
